language: rust
rust:
  - nightly
cache: cargo
sudo: false
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libgtest-dev libboost-dev libxml2-dev cmake
  - sudo wget https://github.com/google/googletest/archive/release-1.8.1.tar.gz
  - sudo tar xf release-1.8.1.tar.gz
  - cd googletest-release-1.8.1
  - sudo cmake -DBUILD_SHARED_LIBS=ON .
  - sudo make
  - sudo cp -a include/gtest /usr/include
  - sudo cp -a libgtest_main.so libgtest.so /usr/lib/
  - git clone https://github.com/ContinuumIO/libhdfs3-downstream.git libhdfs3
  - cd libhdfs3/libhdfs3
  - cmake

script:
  - cargo build --verbose --all
  - cargo test --verbose --all
  - rustdoc --test readme.md -L target
after_success:
  - travis-cargo coveralls --no-sudo

notifications:
  email:
    on_success: never
addons:
  apt:
    packages:
      - libssl-dev
      - libgtest-dev
      - libboost-dev
      - libxml2-dev
