language: rust
rust:
  - nightly
cache: cargo
sudo: false

jobs:
  include:
    - stage: build googletest
      script: build_utils/googletest.sh
    - stage: build libhdfs3
      script: build_utils/libhdfs3.sh
    - stage: build and test hdfs-cmd
      script:
        - cargo build --verbose --all
        - cargo test --verbose --all
        - rustdoc --test readme.md -L target

after_success:
  - travis-cargo coveralls --no-sudo

notifications:
  email:
    on_success: never
addons:
  apt:
    packages:
      - openssl-dev
      - libgtest-dev
      - libboost-dev
      - libxml2-dev
      - libkrb5-dev
      - libgsasl7-dev
      - uuid-dev
